version: 1
disable_existing_loggers: False
formatters:
        simple:
            format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
            datefmt: '%F %T'
        shadow_format:
            format: "%(levelname)s: %(asctime)s: %(filename)s:%(lineno)d * %(thread)d %(message)s"
            datefmt: '%m-%d %H:%M:%S'

handlers:
    console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: simple
            stream: ext://sys.stdout
    crnn_file_handler:
            class: logging.handlers.TimedRotatingFileHandler
            level: DEBUG
            formatter: simple
            filename: ./logs/crnn.log
            backupCount: 20
            encoding: utf8
            when: D
            interval: 1
    factory_file_handler:
            class: logging.handlers.TimedRotatingFileHandler
            level: DEBUG
            formatter: simple
            filename: ./logs/factory.log
            backupCount: 20
            encoding: utf8
            when: D
            interval: 1
    error_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: ERROR
            formatter: simple
            filename: ./logs/errors.log
            maxBytes: 10485760
            backupCount: 20
            encoding: utf8
loggers:
    # CRNN网络输出
    crnn:
            level: DEBUG
            handlers: [crnn_file_handler]
            propagate: no
    # 图像加载器
    factory:
            level: DEBUG
            handlers: [factory_file_handler]
            propagate: no
root:
    level: INFO
    handlers: [console, crnn_file_handler, factory_file_handler, error_file_handler]